{% set name = "pydifact" %}
{% set version = "0.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pydifact-{{ version }}.tar.gz
  sha256: 972073847edd4095ea9f91810f03f3899ba20997feebe054a8fc85d76f62d7eb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<3.10
  run:
    - python >=3.6,<3.10

test:
  imports:
    - pydifact
    - pydifact.control
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nerdocs/pydifact
  summary: A Python EDI file parser.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
