{% set name = "pydifact" %}
{% set version = "0.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pydifact-{{ version }}.tar.gz
  sha256: 8e27edb34792c9a76b23c9d595fb7f7eba71d71fa48af7349f7776a59ff7e043

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - pydifact
    - pydifact.control
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nerdocs/pydifact
  summary: A Python EDI file parser.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
