{% set name = "pydifact" %}
{% set version = "0.1.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pydifact-{{ version }}.tar.gz
  sha256: a51f357f3eb62c7ff7200d7bba0be06c8d837bc45becd30019feae1079e1392f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<3.10
  run:
    - python >=3.6,<3.10

test:
  imports:
    - pydifact
    - pydifact.control
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nerdocs/pydifact
  summary: A Python EDI file parser.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
