{% set name = "pydifact" %}
{% set version = "0.1.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pydifact-{{ version }}.tar.gz
  sha256: a9fd6093ba653a7f998349cb265b8811fbcdb936bdf8ea2591ffdf42590b8dd6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<3.10
  run:
    - python >=3.6,<3.10

test:
  imports:
    - pydifact
    - pydifact.control
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nerdocs/pydifact
  summary: A Python EDI file parser.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
