{% set name = "pydifact" %}
{% set version = "0.0.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pydifact-{{ version }}.tar.gz
  sha256: c94293cb1b141d09be414f6676f35e5bfcbcaf0874f99639cb0305a9e2b9b972

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - pydifact
    - pydifact.control
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nerdocs/pydifact
  summary: A Python EDI file parser.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
